---

################################################################################
#  description: Apply updates to the installed Ansible kit on CentOS7x
#  usage: ansible-playbook CentOS7x_Apply-Ansible-Updates-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Apply updates to the installed Ansible kit on CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Execute command(s)
# REF: http://docs.ansible.com/ansible/command_module.html
##########################################################

# https://github.com/ActiveState/appdirs/issues/89
  - name: Use pip to update and ensure appdirs is at the latest version
    command: /usr/bin/pip install --upgrade appdirs

  - name: Use pip to update and ensure pip is at the latest version
    command: /usr/bin/pip install --upgrade pip

  - name: Use pip to update and ensure pywinrm is at the latest version
    command: /usr/bin/pip install --upgrade pywinrm

  - name: Use pip to update and ensure ansible is at the latest version
    command: /usr/bin/pip install --upgrade ansible

  - name: Use pip to update and ensure clc-sdk is at the latest version
    command: /usr/bin/pip install --upgrade clc-sdk

  - name: Use pip to update and ensure clc-ansible-module is at the latest version
    command: /usr/bin/pip install --upgrade clc-ansible-module
